#!/usr/bin/perl -w

#lsso: by Jason Burrell <jburrell@mac.edu>

#This lists the so (libs) used by OSF/1 / Digital UNIX / Compaq Tru64 UNIX
#dynamic executables. One could read the info from the file, but this script
#works for a quick-and-dirty program. As it looks at all strings, it may
#specify libs that aren't used. Also, this isn't as reliable as reading the
#info that the dynamic linker reads from the binary.

#Actually, this script should work for many dynamic executable formats.

#make sure you have strings(1), it's part of binutils

unless($ARGV[0])
{
    print "$0: usage: $0 binary-file\n";
    exit;
}
open Strings, "strings $ARGV[0]|";
while(<Strings>)
{
    print $_ if m/\.so$/;
    print $_ if m/\.so\./;
}
